[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
next-intl-extractor = { path = "../extractor" }
anyhow = "1.0.86"
clap = "4.2.1"
glob = "0.3.1"
tracing = "0.1"
tracing-subscriber = "0.3"
