name: ci
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
    name: ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}
      - name: Build
        run: cargo build --target ${{ matrix.settings.target }}
